apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: @h0lant1e5@h0lant1e5SUPERGAMING
  MYSQL_DATABASE: exampledb
  MYSQL_USER: mqtt_user
  MYSQL_PASSWORD: @h0lant1e5@h0lant1e5SUPERGAMING
