apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: superKuber123!
  MYSQL_DATABASE: kubernets_db
  MYSQL_USER: kuber_user
  MYSQL_PASSWORD: superKuber123!
